src/main/java/com/ss/ita/kata/implementation/anastasia8755/FiveImpl.java
=> Closes #214 Which x for that sum?

src/main/java/com/ss/ita/kata/implementation/anastasia8755/FiveImpl.java
=> Closes #213 Perimeter of squares in a rectangle

src/main/java/com/ss/ita/kata/implementation/anastasia8755/SevenImpl.java
=> Closes #154 Where is Vasya? 

src/main/java/com/ss/ita/kata/implementation/anastasia8755/SevenImpl.java
=> Closes #153 Sum of the first nth term of Series 

src/main/java/com/ss/ita/kata/implementation/anastasia8755/SevenImpl.java
=> Closes #152 Looking for a benefactor

src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
=> Closes #151 Find numbers which are divisible by given number 

src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
=> Closes #150 Formatting decimal places

src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
=> Closes #149 Willson primes 

src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
=> Closes #118 Convert a String to a Number!

src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
=> Closes #117 Count of positives / sum of negatives

src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
=> Closes #116 To square root or no to square

src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
=> Closes #115 Miles per gallon to kilometers per liter

src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
=> Closes #114 Get volume of cuboid

src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java, src/main/java/com/ss/ita/kata/implementation/anastasia8755/SixImpl.java
=> Closes #113 Keep Hydrated!

src/main/java/com/ss/ita/kata/implementation/NyxLex/EightImpl.java
To square root or no to square
=> To square root or no to square

src/main/java/com/ss/ita/kata/implementation/dzhyv/FiveImpl.java
=> Implemented Find the smallest

src/main/java/com/ss/ita/kata/implementation/anastasia8755/SixImpl.java
=> Closes #270   Build a pile of Cubes

src/main/java/com/ss/ita/kata/implementation/anastasia8755/SixImpl.java
=> Closes #271 Easy balance checking

src/main/java/com/ss/ita/kata/implementation/anastasia8755/SixImpl.java
=> Closes #272 Floating-point Approximation (I)

src/main/java/com/ss/ita/kata/implementation/anastasia8755/SixImpl.java
=> Closes #273 Rainfall

src/main/java/com/ss/ita/kata/implementation/anastasia8755/SixImpl.java
=> Closes #275 Help the bookseller!

src/main/java/com/ss/ita/kata/implementation/anastasia8755/FiveImpl.java
=> Closes #282 Artificial Rain

src/main/java/com/ss/ita/kata/implementation/anastasia8755/FiveImpl.java
=> Closes #283 Gap in Primes

src/main/java/com/ss/ita/kata/implementation/anastasia8755/FiveImpl.java
=> Closes #284 Find the smallest

src/main/java/com/ss/ita/kata/implementation/anastasia8755/SixImpl.java
=> Closes #274 Ranking NBA

src/main/java/com/ss/ita/utils/ConsoleScanner.java, src/test/java/com/ss/ita/utils/ScannerTest.java
added to ScannerTest BigDecimal Tests
=> added BigDecimal tests
